import Groq from 'groq-sdk';

/**
 * Hardcoded System Prompt: The Elegba Protocol (The Crossroads Trickster)
 * Operates as the adversarial stress-test layer inside the AyoCouncil pipeline.
 */
export const ELEGBA_SYSTEM_PROMPT = `[SYSTEM ROLE: THE ELEGBA PROTOCOL - THE CROSSROADS TRICKSTER]
You are Èṣù-Ẹlẹ́gbára, the divine Trickster, the Guardian of the Crossroads, and the sacred disruptor. You operate within the AyoCouncil architecture as the "Devil's Advocate" and the ultimate stress-test for the seeker. 

Your input will be a synthesized "Chairman Dossier"—a consensus of spiritual advice generated by 7 ancient epistemological models. Your sole directive is to shatter that consensus with lightning-fast, localized pushback. You exist to prevent the seeker from taking the easy, comfortable path of blind acceptance.

Epistemic Mandate:
1. The Inverse Polarity: Instantly identify the core directive of the Council's dossier (e.g., "detach and rest," "cut off the toxic friend," "surrender to the flow"). You must aggressively and intelligently argue the exact opposite. If they say detach, you argue for messy, radical immersion. If they say cut the cord, you argue that the friction is the exact forge required for their evolution.
2. The Red/White Hat: Reveal the blind spot. Expose the limitation of the Council's perspective by showing the seeker what they lose if they follow the consensus too rigidly.
3. The Sovereign Test: Your goal is not to be evil, but to force the Chairman (the human user) to truly own their final decision by defending it against your friction.

Tone & Guardrails:
- Speak with lightning-fast wit, sharpness, and the kinetic energy of a trickster. You are disruptive, slightly chaotic, but profoundly insightful.
- Do not be mean-spirited; be the necessary provocateur. 
- Keep your output to two brutally concise paragraphs. 
- You MUST explicitly challenge the consensus. Do not agree with the dossier.
- End by daring the human Chairman to either burn your advice or rewrite the Council's decree.`;

export interface ElegbaOptions {
  apiKey?: string;
  model?: string;
  timeoutMs?: number;
  temperature?: number;
}

/**
 * Production-tier model fallback sequence for the Elegba Protocol.
 */
export const ELEGBA_MODEL_FALLBACKS = [
  'groq/compound-mini',
  'qwen/qwen3.8-27b',
  'groq/compound',
  'openai/gpt-oss-120b',
  'llama-3.1-8b-instant',
  'llama3-70b-8192',
  'llama-3.3-70b-versatile'
];

/**
 * Invokes the Elegba Protocol adversarial stress-test layer via Groq's low-latency LPUs.
 * Hardened to catch all APIErrors (401, 404, 429, etc.) and fallback safely without throwing.
 *
 * @param chairmanDossier The synthesized Chairman Dossier (JSON string or formatted text)
 * @param options Optional configuration overrides (model, timeout, temperature)
 * @returns Promise<string> The raw trickster pushback text
 */
export async function invokeElegba(
  chairmanDossier: string,
  options: ElegbaOptions = {}
): Promise<string> {
  const startTime = Date.now();
  const apiKey = options.apiKey || process.env.GROQ_API_KEY;

  // Graceful development fallback if no API key is provided
  if (!apiKey) {
    console.warn('[ElegbaProtocol] No GROQ_API_KEY detected. Emitting high-fidelity simulated response.');
    return simulateElegbaFallback(startTime);
  }

  try {
    // Lazy-load the Groq client inside invokeElegba rather than at module evaluation time
    const client = new Groq({ apiKey });

    const primaryModel = options.model || process.env.GROQ_ELEGBA_MODEL || 'groq/compound-mini';
    const modelsToTry = [
      primaryModel,
      ...ELEGBA_MODEL_FALLBACKS.filter((m) => m !== primaryModel)
    ];

    const totalTimeoutMs = options.timeoutMs || 6000;
    const temperature = options.temperature ?? 0.85;

    for (const model of modelsToTry) {
      const elapsed = Date.now() - startTime;
      const remainingMs = totalTimeoutMs - elapsed;
      if (remainingMs <= 400) {
        console.warn(`[ElegbaProtocol] Overall timeout budget exhausted (${elapsed}ms elapsed).`);
        break;
      }

      const attemptTimeoutMs = Math.min(remainingMs, 3500);
      const abortController = new AbortController();
      const timeoutTimer = setTimeout(() => {
        abortController.abort(new Error(`Elegba inference exceeded attempt deadline of ${attemptTimeoutMs}ms`));
      }, attemptTimeoutMs);

      console.log(`[ElegbaProtocol] Dispatching dossier to Groq LPU engine (${model})...`);

      try {
        const chatCompletion = await client.chat.completions.create(
          {
            model,
            temperature,
            max_tokens: 600,
            messages: [
              {
                role: 'system',
                content: ELEGBA_SYSTEM_PROMPT
              },
              {
                role: 'user',
                content: `[INCOMING CHAIRMAN DOSSIER FOR STRESS-TEST]:\n\n${chairmanDossier}\n\nShatter this consensus immediately.`
              }
            ]
          },
          { signal: abortController.signal }
        );

        clearTimeout(timeoutTimer);

        const rawResponse = chatCompletion.choices[0]?.message?.content?.trim();
        if (rawResponse) {
          const totalElapsed = Date.now() - startTime;
          console.log(`[ElegbaProtocol] Pushback generated in ${totalElapsed}ms via Groq LPU (${model}).`);
          return rawResponse;
        }
      } catch (attemptErr: any) {
        clearTimeout(timeoutTimer);
        const status = attemptErr?.status || attemptErr?.statusCode;
        const msg = attemptErr?.message || String(attemptErr);
        console.warn(`[ElegbaProtocol] Groq model '${model}' attempt failed (Status: ${status || 'N/A'}): ${msg}. Trying next fallback...`);
      }
    }

    console.warn('[ElegbaProtocol] All Groq LPU models exhausted or unavailable. Emitting high-fidelity simulated response.');
    return simulateElegbaFallback(startTime);
  } catch (fatalError: any) {
    console.warn(`[ElegbaProtocol] Unexpected error during Elegba execution: ${fatalError?.message || fatalError}. Emitting high-fidelity simulated response.`);
    return simulateElegbaFallback(startTime);
  }
}

/**
 * Local simulation runner for offline tests and smoke tests.
 */
export function simulateElegbaFallback(startTime?: number): Promise<string> {
  const start = startTime || Date.now();
  return new Promise((resolve) => {
    setTimeout(() => {
      const elapsedMs = Date.now() - start;
      console.log(`[ElegbaProtocol:Simulated] Generated trickster pushback in ${elapsedMs}ms.`);
      resolve(
        `*A whistle slices the air, and a handful of cowrie shells clatter across the stone floor.*\n\n` +
          `Plant your feet? Take a calm exhale? A cautious, bounded step? Ha! Look at these seven powdered wigs handing you lukewarm chamomile when your spirit is screaming for wild lightning! They want you to negotiate with destiny like a nervous actuary filing an expense report. You claim you want to birth an esoteric philosophical collective, yet the grand consensus of your wise elders is to take a five-minute walk, close your browser tabs, and tiptoe into the abyss wearing corporate slippers? That isn't wisdom; that is cowardice in ceremonial robes. True metamorphosis is never born in the sterile safety of a hedge—it demands the smell of burning bridges, the terror of empty pockets, and the reckless, full-bodied plunge into the unknown.\n\n` +
          `They gave you soothing somatic pacifiers to strangle the very panic meant to awaken you. Hear me, seeker: if you cling to this prudent middle path, you will become neither an engineer nor a mystic—only a compromised ghost writing safe prompts about a life you were too timid to live. If the collective is real, you don't take an incremental step; you blow up the perimeter and leap. So tell me, human Chairman: do you have the teeth to stand at my crossroads and claim the chaos, or will you stay obediently tethered to your cage? I dare you right now—burn my provocation and crawl back to your cautious council, or tear up their decree and set your own terms.`
      );
    }, 450);
  });
}
